### ISSUE TITLE
float value in csv is not parsed correctly in the culture that separated comma / 小数点の区切りがカンマのculture環境で正常にcsvがパースされない。

### ISSUE THREAD

**Issue by youten** [unity3d-jp/UnityChanSpringBone#16]
float value in csv is not parsed correctly in the culture that separated comma
小数点の区切りがカンマのculture環境で正常にcsvがパースされない。

using `CultureInfo.CurrentCulture = new CultureInfo(“pt-BR”);`, can reproduce on Unity Editor.
`CultureInfo.CurrentCulture = new CultureInfo(“pt-BR”);` あたりで適当にcultureを変更するとUnityエディタ上でもおかしくなるのが再現できる。

このあたりが `CultureInfo.InvariantCulture` 対応である必要がある
https://github.com/unity3d-jp/UnityChanSpringBone/blob/release/1.1/Runtime/Utility/ObjectBuilding/StringQueueObjectBuilder.cs#L14
https://github.com/unity3d-jp/UnityChanSpringBone/blob/release/1.1/Runtime/Utility/ObjectBuilding/StringQueueObjectBuilder.cs#L24-L26
https://github.com/unity3d-jp/UnityChanSpringBone/blob/release/1.1/Runtime/Utility/ObjectBuilding/StringQueueObjectBuilder.cs#L166

**Comment by H3idi-X** [comment]
Thanks for contributing us and apologies for this late reply. We didn't have time to see this because of Siggraph 2021 preparations and so on.
I've checked rinna's PR(#18). Is that additional to youten's one(#17)?　As far as, I see. rinna's PR(#18) is not dealing with some parse methods yoten has mended in  StringQueueObjectBuilder.cs.

**Comment by H3idi-X** [comment]
In that case, youten need to agree CLA, This is necessary to submit PR to Unity github.

**Comment by H3idi-X** [comment]
Thanks both of you. We adopted riina's fix. I believe the fix is right. 
However, 


- Calling  CultureInfo.CurrentCulture = new CultureInfo(“pt-BR”);
- "Save to CSV".
- Then do "Set up from CSV".

Some times Single.parse() called from [here](https://github.com/unity3d-jp/UnityChanSpringBone/blob/ead9ef112e25cce462b553f35fb1b2bd20918c40/Runtime/Utility/ObjectBuilding/StringQueueObjectBuilder.cs#L167) fails to parse float when "," is used as decimal point mark.

I'm still on investigation.
